### ISSUE TITLE
segment fault

### ISSUE THREAD

**Issue by freedai** [xelerance/Openswan#306]
https://github.com/xelerance/Openswan/blob/6055fc6fa444f3d5b89ad0f7d3ec277eedaa9282/programs/pluto/kernel.c#L1184

when using ikev2, we encounter core dump at this line.

>(gdb) bt
#0  addrtypeof (src=0x2a8) at /builddir/build/BUILD/openswan-2.6.50/lib/libopenswan/addrtypeof.c:25
#1  0x00007f58d13077d8 in eroute_connection (st=0x0, sr=0x7ffe477e7a70, spi=17825792, proto=4, esatype=ET_IPIP, proto_info=0x7ffe477e7818, op=1, opname=0x7f58d1375fca "add", policy_label=0x0)
    at /builddir/build/BUILD/openswan-2.6.50/programs/pluto/kernel.c:1184
#2  0x00007f58d131252b in pfkey_sag_eroute (st=0x7f58d1a86f80, sr=0x7ffe477e7a70, op=<optimized out>, opname=<optimized out>) at /builddir/build/BUILD/openswan-2.6.50/programs/pluto/kernel_pfkey.c:1431
#3  0x00007f58d1308aea in route_and_eroute (c=0x7f58d1a82fe0, sr=0x7ffe477e7a70, orig_sr=0x7f58d1a83080, st=0x7f58d1a86f80) at /builddir/build/BUILD/openswan-2.6.50/programs/pluto/kernel.c:2661
#4  0x00007f58d130c14f in install_ipsec_sa (parent_st=0x7f58d1a84b30, st=0x7f58d1a86f80, inbound_also=<optimized out>) at /builddir/build/BUILD/openswan-2.6.50/programs/pluto/kernel.c:2959
#5  0x00007f58d12f41b4 in quick_inR1_outI2_cryptotail (dh=<optimized out>, r=<optimized out>) at /builddir/build/BUILD/openswan-2.6.50/programs/pluto/ikev1_quick.c:2608
#6  0x00007f58d12f4595 in quick_inR1_outI2 (md=0x7f58d1a85d30) at /builddir/build/BUILD/openswan-2.6.50/programs/pluto/ikev1_quick.c:2405
#7  0x00007f58d12ebe5f in process_packet_tail (mdp=0x7f58d15b6c88 <md.12031>) at /builddir/build/BUILD/openswan-2.6.50/programs/pluto/ikev1.c:1880
#8  0x00007f58d1315558 in process_packet (mdp=0x7f58d15b6c88 <md.12031>) at /builddir/build/BUILD/openswan-2.6.50/programs/pluto/demux.c:170
#9  0x00007f58d1315afc in comm_handle (ifp=0x7f58d1a7c6e0) at /builddir/build/BUILD/openswan-2.6.50/programs/pluto/demux.c:226
#10 0x00007f58d12e394b in call_server () at /builddir/build/BUILD/openswan-2.6.50/programs/pluto/server.c:766
#11 0x00007f58d12e1075 in main (argc=32, argv=0x7ffe477e8cf8) at /builddir/build/BUILD/openswan-2.6.50/programs/pluto/plutomain.c:1126

**Comment by shussain** [comment]
Thank you for informing us.

Can you please provide your ipsec configuration?

**Comment by freedai** [comment]
# ---------------------------------------------------- #
# /etc/ipsec.conf - Openswan IPSec configuration file
# ---------------------------------------------------- #
#
# This file is automatically generated.
# Do not manually edit this file, changes will not survive.
#

version 2.0

config setup
    interfaces="ipsec0=eth1"
    klipsdebug="none"
    plutodebug="raw klips pfkey natt nattraversal"
    uniqueids=yes
    virtual_private=%v4:10.0.0.0/8,%v4:172.16.0.0/12,%v4:192.168.0.0/16,%v4:!192.168.11.0/24
    nat_traversal=yes
    nhelpers=0
    dumpdir=/tmp

conn %default
    authby=rsasig
    leftrsasigkey=%cert
    rightrsasigkey=%cert
    keyingtries=2
    rekeymargin="10"
    leftupdown=/etc/ipsec.d/scripts/ipsec.updown
    rightupdown=/etc/ipsec.d/scripts/ipsec.updown
    leftsendcert=always
    ike=3des-sha1,aes-sha1,3des-md5,aes-md5,aes256-sha1,aes256-md5

# Disable opportunistic encryption
conn block
    auto=ignore

conn private
    auto=ignore

conn private-or-clear
    auto=ignore

conn clear-or-private
    auto=ignore

conn clear
    auto=ignore

conn packetdefault
    auto=ignore

include /etc/ipsec.d/conn/connection-*-*-*

**Comment by freedai** [comment]
conn connection-10.50.10.109-10.50.10.104-0
    right=10.50.10.104
    left=10.50.10.109
    authby=secret
    rightid="@chau-utm-66-2.twplatforms.com"
    leftid="@cyu-utm64-01.twplatforms.com"
    leftsubnet=192.168.11.0/24
    rightsubnets=192.168.162.0/24
    auto=start
    ikelifetime=3600s
    keylife=28800s
    dpddelay=30
    dpdtimeout=120
    dpdaction=restart_by_peer
    leftupdown=""
    leftnexthop=10.50.10.104
    rightnexthop=10.50.10.109
    pfs=no
    ikev2=insist
    ike=aes256-sha1;dh22,aes256-sha2_256;dh22,aes128-sha1;dh22,aes128-sha2_256;dh22,3des-sha1;dh22
    phase2alg=aes256-sha1,3des-sha1,aes128-sha1

**Comment by shussain** [comment]
@freedai thank you.

Does this issue occur when you build and use the 2.6.51dev branch?

**Comment by freedai** [comment]
The version I'm using is 2.6.50
